# Generated by Django 4.1.5 on 2025-04-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospectivity', '0002_alter_prospectivityproject_user_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geospatialdatasets',
            name='crs',
            field=models.CharField(choices=[('GCS', 'GCS (Geological Coordinate System)'), ('PCS', 'PCS (Projected Coordinate System)')], max_length=50, verbose_name='Coordinate reference system'),
        ),
    ]
