# Generated by Django 4.1.5 on 2025-04-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospectivity', '0003_alter_geospatialdatasets_crs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geospatialdatasets',
            name='crs',
            field=models.CharField(choices=[('GCS', 'Gcs'), ('PCS', 'Pcs')], max_length=50, verbose_name='Coordinate reference system'),
        ),
    ]
