# Generated by Django 4.1.5 on 2025-04-27 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prospectivity', '0004_alter_geospatialdatasets_crs'),
    ]

    operations = [
        migrations.AddField(
            model_name='geospatialdatasets',
            name='geometry_types',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='prospectivityproject',
            name='user_updated',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='updated by user'),
        ),
        migrations.AlterModelTable(
            name='prospectivityproject',
            table=None,
        ),
    ]
