# Generated by Django 4.1.5 on 2025-04-27 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prospectivity', '0005_geospatialdatasets_geometry_types_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospectivityproject',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='updated by user'),
        ),
    ]
