# Generated by Django 4.1.5 on 2025-05-11 03:25

from django.db import migrations, models
import prospectivity.models


class Migration(migrations.Migration):

    dependencies = [
        ('prospectivity', '0007_alter_geospatialdatasets_dataset_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='geospatialdatasets',
            name='processed_file',
            field=models.FileField(blank=True, help_text='Processed file after tasks', null=True, upload_to=prospectivity.models.dataset_upload_path),
        ),
        migrations.AddField(
            model_name='geospatialdatasets',
            name='status',
            field=models.CharField(choices=[('Raw', 'Raw'), ('Validated', 'Validated'), ('Preprocessing', 'Preprocessing'), ('Running', 'Running'), ('Ready', 'Ready'), ('Failed', 'Failed')], default='Raw', max_length=20),
        ),
        migrations.AddField(
            model_name='geospatialdatasets',
            name='task_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geospatialdatasets',
            name='thumbnail',
            field=models.FileField(blank=True, help_text='Thumbnail for visualization', null=True, upload_to='thumbnails/'),
        ),
        migrations.AddField(
            model_name='mlmodelrun',
            name='task_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospectivityproject',
            name='target_crs',
            field=models.CharField(default='EPSG:4326', help_text='Target CRS for the project datasets', max_length=50),
        ),
    ]
